name: Build + Push Frontend

on:
  push:
    tags:
      - "frontend-*-*.*.*"

jobs:
  build:
    name: Build frontend
    environment:
      name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract tag info
        id: extract_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          APP_ENVIRONMENT=${TAG_NAME%-*}
          APP=${APP_ENVIRONMENT%-*}
          ENVIRONMENT=${APP_ENVIRONMENT#*-}
          echo "tag_name=${TAG_NAME}" >> "$GITHUB_ENV"
          echo "app_environment=${APP_ENVIRONMENT}" >> "$GITHUB_ENV"
          echo "app=${APP}" >> "$GITHUB_ENV"
          echo "environment=${ENVIRONMENT}" >> "$GITHUB_ENV"

          echo "action_state=yellow" >> "$GITHUB_ENV"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.app_environment }}:${{ steps.extract_tag.outputs.tag_name }}
