name: Build + Push Frontend

on: push

jobs:
  build:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build
        uses: docker/build-push-action@v2
