name: Build + Push Frontend # git add . && git commit -m "updates" && git tag -f frontend-staging-1.0.0 && git push origin -f frontend-staging-1.0.0

on:
  push:
    tags:
      - "frontend-*-*.*.*"

jobs:
  build:
    name: Build frontend
    environment:
      name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract tag info
        id: extract_tag
        run: |
          echo ${GITHUB_REF} 
          TAG_NAME=${GITHUB_REF#refs/tags/} 
          echo "tag_name=${TAG_NAME}" >> "$GITHUB_ENV" 
          APP_ENVIRONMENT=${TAG_NAME%-*} 
          echo "app_environment=${APP_ENVIRONMENT}" >> "$GITHUB_ENV" 
          APP=${APP_ENVIRONMENT%-*} 
          echo "app=${APP}" >> "$GITHUB_ENV" 
          ENVIRONMENT=${APP_ENVIRONMENT#*-} 
          echo "environment=${ENVIRONMENT}" >> "$GITHUB_ENV"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: openq/${{ env.tag_name }}
